---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    targetPort: 8081
    protocol: TCP
  selector:
    app: hello-world
